### Registering User
POST http://localhost:3000/api/v1/auth/register

{
  "name" : "doublechoc",
  "email":"doublechoc@gmail.com",
  "password":"yahut"
}

### Login User
POST http://localhost:3000/api/v1/auth/login

{
  "email":"doublechoc@gmail.com",
  "password":"yahut"
}


